// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: payment-service/proto/payment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_PROCESSING  PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_COMPLETED   PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 4
	PaymentStatus_PAYMENT_STATUS_CANCELLED   PaymentStatus = 5
	PaymentStatus_PAYMENT_STATUS_REFUNDED    PaymentStatus = 6
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_PROCESSING",
		3: "PAYMENT_STATUS_COMPLETED",
		4: "PAYMENT_STATUS_FAILED",
		5: "PAYMENT_STATUS_CANCELLED",
		6: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_PROCESSING":  2,
		"PAYMENT_STATUS_COMPLETED":   3,
		"PAYMENT_STATUS_FAILED":      4,
		"PAYMENT_STATUS_CANCELLED":   5,
		"PAYMENT_STATUS_REFUNDED":    6,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_service_proto_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_payment_service_proto_payment_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_service_proto_payment_proto_rawDescGZIP(), []int{0}
}

type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_CREDIT_CARD PaymentMethod = 1
	PaymentMethod_PAYMENT_METHOD_METAMASK    PaymentMethod = 2
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "PAYMENT_METHOD_CREDIT_CARD",
		2: "PAYMENT_METHOD_METAMASK",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED": 0,
		"PAYMENT_METHOD_CREDIT_CARD": 1,
		"PAYMENT_METHOD_METAMASK":    2,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_service_proto_payment_proto_enumTypes[1].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_payment_service_proto_payment_proto_enumTypes[1]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_payment_service_proto_payment_proto_rawDescGZIP(), []int{1}
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`
	PaymentMethod PaymentMethod          `protobuf:"varint,7,opt,name=payment_method,json=paymentMethod,proto3,enum=payment.PaymentMethod" json:"payment_method,omitempty"`
	TransactionId string                 `protobuf:"bytes,8,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_payment_service_proto_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Payment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Payment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Payment) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *Payment) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Payment) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Payment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type InitiatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethod PaymentMethod          `protobuf:"varint,5,opt,name=payment_method,json=paymentMethod,proto3,enum=payment.PaymentMethod" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiatePaymentRequest) Reset() {
	*x = InitiatePaymentRequest{}
	mi := &file_payment_service_proto_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatePaymentRequest) ProtoMessage() {}

func (x *InitiatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatePaymentRequest.ProtoReflect.Descriptor instead.
func (*InitiatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_payment_proto_rawDescGZIP(), []int{1}
}

func (x *InitiatePaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *InitiatePaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InitiatePaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *InitiatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *InitiatePaymentRequest) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

type CreditCardPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	CardInfo      *CreditCardInfo        `protobuf:"bytes,2,opt,name=card_info,json=cardInfo,proto3" json:"card_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditCardPaymentRequest) Reset() {
	*x = CreditCardPaymentRequest{}
	mi := &file_payment_service_proto_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditCardPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditCardPaymentRequest) ProtoMessage() {}

func (x *CreditCardPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditCardPaymentRequest.ProtoReflect.Descriptor instead.
func (*CreditCardPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CreditCardPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreditCardPaymentRequest) GetCardInfo() *CreditCardInfo {
	if x != nil {
		return x.CardInfo
	}
	return nil
}

type CreditCardInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CardNumber     string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	ExpiryMonth    string                 `protobuf:"bytes,2,opt,name=expiry_month,json=expiryMonth,proto3" json:"expiry_month,omitempty"`
	ExpiryYear     string                 `protobuf:"bytes,3,opt,name=expiry_year,json=expiryYear,proto3" json:"expiry_year,omitempty"`
	Cvv            string                 `protobuf:"bytes,4,opt,name=cvv,proto3" json:"cvv,omitempty"`
	CardholderName string                 `protobuf:"bytes,5,opt,name=cardholder_name,json=cardholderName,proto3" json:"cardholder_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreditCardInfo) Reset() {
	*x = CreditCardInfo{}
	mi := &file_payment_service_proto_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditCardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditCardInfo) ProtoMessage() {}

func (x *CreditCardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditCardInfo.ProtoReflect.Descriptor instead.
func (*CreditCardInfo) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CreditCardInfo) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CreditCardInfo) GetExpiryMonth() string {
	if x != nil {
		return x.ExpiryMonth
	}
	return ""
}

func (x *CreditCardInfo) GetExpiryYear() string {
	if x != nil {
		return x.ExpiryYear
	}
	return ""
}

func (x *CreditCardInfo) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *CreditCardInfo) GetCardholderName() string {
	if x != nil {
		return x.CardholderName
	}
	return ""
}

type MetaMaskPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	WalletAddress string                 `protobuf:"bytes,2,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaMaskPaymentRequest) Reset() {
	*x = MetaMaskPaymentRequest{}
	mi := &file_payment_service_proto_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaMaskPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaMaskPaymentRequest) ProtoMessage() {}

func (x *MetaMaskPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaMaskPaymentRequest.ProtoReflect.Descriptor instead.
func (*MetaMaskPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_payment_proto_rawDescGZIP(), []int{4}
}

func (x *MetaMaskPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *MetaMaskPaymentRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

type MetaMaskPaymentResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PaymentId        string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	TransactionHash  string                 `protobuf:"bytes,2,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	ContractAddress  string                 `protobuf:"bytes,3,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	PaymentAmountWei string                 `protobuf:"bytes,4,opt,name=payment_amount_wei,json=paymentAmountWei,proto3" json:"payment_amount_wei,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MetaMaskPaymentResponse) Reset() {
	*x = MetaMaskPaymentResponse{}
	mi := &file_payment_service_proto_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaMaskPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaMaskPaymentResponse) ProtoMessage() {}

func (x *MetaMaskPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaMaskPaymentResponse.ProtoReflect.Descriptor instead.
func (*MetaMaskPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_payment_proto_rawDescGZIP(), []int{5}
}

func (x *MetaMaskPaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *MetaMaskPaymentResponse) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *MetaMaskPaymentResponse) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *MetaMaskPaymentResponse) GetPaymentAmountWei() string {
	if x != nil {
		return x.PaymentAmountWei
	}
	return ""
}

type ConfirmMetaMaskPaymentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentId       string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	TransactionHash string                 `protobuf:"bytes,2,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfirmMetaMaskPaymentRequest) Reset() {
	*x = ConfirmMetaMaskPaymentRequest{}
	mi := &file_payment_service_proto_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmMetaMaskPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmMetaMaskPaymentRequest) ProtoMessage() {}

func (x *ConfirmMetaMaskPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmMetaMaskPaymentRequest.ProtoReflect.Descriptor instead.
func (*ConfirmMetaMaskPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_payment_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmMetaMaskPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *ConfirmMetaMaskPaymentRequest) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_payment_service_proto_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_payment_proto_rawDescGZIP(), []int{7}
}

func (x *GetPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type GetPaymentsByOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentsByOrderRequest) Reset() {
	*x = GetPaymentsByOrderRequest{}
	mi := &file_payment_service_proto_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentsByOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentsByOrderRequest) ProtoMessage() {}

func (x *GetPaymentsByOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentsByOrderRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentsByOrderRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_payment_proto_rawDescGZIP(), []int{8}
}

func (x *GetPaymentsByOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetPaymentsByOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentsByOrderResponse) Reset() {
	*x = GetPaymentsByOrderResponse{}
	mi := &file_payment_service_proto_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentsByOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentsByOrderResponse) ProtoMessage() {}

func (x *GetPaymentsByOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentsByOrderResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentsByOrderResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_payment_proto_rawDescGZIP(), []int{9}
}

func (x *GetPaymentsByOrderResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

type UpdatePaymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentStatusRequest) Reset() {
	*x = UpdatePaymentStatusRequest{}
	mi := &file_payment_service_proto_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentStatusRequest) ProtoMessage() {}

func (x *UpdatePaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_payment_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePaymentStatusRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *UpdatePaymentStatusRequest) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *UpdatePaymentStatusRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *UpdatePaymentStatusRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetPendingPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingPaymentsRequest) Reset() {
	*x = GetPendingPaymentsRequest{}
	mi := &file_payment_service_proto_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingPaymentsRequest) ProtoMessage() {}

func (x *GetPendingPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingPaymentsRequest.ProtoReflect.Descriptor instead.
func (*GetPendingPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_payment_proto_rawDescGZIP(), []int{11}
}

func (x *GetPendingPaymentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPendingPaymentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPendingPaymentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetPendingPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingPaymentsResponse) Reset() {
	*x = GetPendingPaymentsResponse{}
	mi := &file_payment_service_proto_payment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingPaymentsResponse) ProtoMessage() {}

func (x *GetPendingPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_payment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingPaymentsResponse.ProtoReflect.Descriptor instead.
func (*GetPendingPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_payment_proto_rawDescGZIP(), []int{12}
}

func (x *GetPendingPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *GetPendingPaymentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RetryPaymentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PaymentId        string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	NewPaymentMethod PaymentMethod          `protobuf:"varint,2,opt,name=new_payment_method,json=newPaymentMethod,proto3,enum=payment.PaymentMethod" json:"new_payment_method,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RetryPaymentRequest) Reset() {
	*x = RetryPaymentRequest{}
	mi := &file_payment_service_proto_payment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPaymentRequest) ProtoMessage() {}

func (x *RetryPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_payment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPaymentRequest.ProtoReflect.Descriptor instead.
func (*RetryPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_payment_proto_rawDescGZIP(), []int{13}
}

func (x *RetryPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *RetryPaymentRequest) GetNewPaymentMethod() PaymentMethod {
	if x != nil {
		return x.NewPaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

var File_payment_service_proto_payment_proto protoreflect.FileDescriptor

const file_payment_service_proto_payment_proto_rawDesc = "" +
	"\n" +
	"#payment-service/proto/payment.proto\x12\apayment\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb2\x03\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12.\n" +
	"\x06status\x18\x06 \x01(\x0e2\x16.payment.PaymentStatusR\x06status\x12=\n" +
	"\x0epayment_method\x18\a \x01(\x0e2\x16.payment.PaymentMethodR\rpaymentMethod\x12%\n" +
	"\x0etransaction_id\x18\b \x01(\tR\rtransactionId\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xbf\x01\n" +
	"\x16InitiatePaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12=\n" +
	"\x0epayment_method\x18\x05 \x01(\x0e2\x16.payment.PaymentMethodR\rpaymentMethod\"o\n" +
	"\x18CreditCardPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x124\n" +
	"\tcard_info\x18\x02 \x01(\v2\x17.payment.CreditCardInfoR\bcardInfo\"\xb0\x01\n" +
	"\x0eCreditCardInfo\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12!\n" +
	"\fexpiry_month\x18\x02 \x01(\tR\vexpiryMonth\x12\x1f\n" +
	"\vexpiry_year\x18\x03 \x01(\tR\n" +
	"expiryYear\x12\x10\n" +
	"\x03cvv\x18\x04 \x01(\tR\x03cvv\x12'\n" +
	"\x0fcardholder_name\x18\x05 \x01(\tR\x0ecardholderName\"^\n" +
	"\x16MetaMaskPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12%\n" +
	"\x0ewallet_address\x18\x02 \x01(\tR\rwalletAddress\"\xbc\x01\n" +
	"\x17MetaMaskPaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12)\n" +
	"\x10transaction_hash\x18\x02 \x01(\tR\x0ftransactionHash\x12)\n" +
	"\x10contract_address\x18\x03 \x01(\tR\x0fcontractAddress\x12,\n" +
	"\x12payment_amount_wei\x18\x04 \x01(\tR\x10paymentAmountWei\"i\n" +
	"\x1dConfirmMetaMaskPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12)\n" +
	"\x10transaction_hash\x18\x02 \x01(\tR\x0ftransactionHash\"2\n" +
	"\x11GetPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"6\n" +
	"\x19GetPaymentsByOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"J\n" +
	"\x1aGetPaymentsByOrderResponse\x12,\n" +
	"\bpayments\x18\x01 \x03(\v2\x10.payment.PaymentR\bpayments\"\xb7\x01\n" +
	"\x1aUpdatePaymentStatusRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.payment.PaymentStatusR\x06status\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"^\n" +
	"\x19GetPendingPaymentsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"`\n" +
	"\x1aGetPendingPaymentsResponse\x12,\n" +
	"\bpayments\x18\x01 \x03(\v2\x10.payment.PaymentR\bpayments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"z\n" +
	"\x13RetryPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12D\n" +
	"\x12new_payment_method\x18\x02 \x01(\x0e2\x16.payment.PaymentMethodR\x10newPaymentMethod*\xde\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19PAYMENT_STATUS_PROCESSING\x10\x02\x12\x1c\n" +
	"\x18PAYMENT_STATUS_COMPLETED\x10\x03\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x04\x12\x1c\n" +
	"\x18PAYMENT_STATUS_CANCELLED\x10\x05\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x06*l\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_CREDIT_CARD\x10\x01\x12\x1b\n" +
	"\x17PAYMENT_METHOD_METAMASK\x10\x022\xe1\x05\n" +
	"\x0ePaymentService\x12D\n" +
	"\x0fInitiatePayment\x12\x1f.payment.InitiatePaymentRequest\x1a\x10.payment.Payment\x12O\n" +
	"\x18ProcessCreditCardPayment\x12!.payment.CreditCardPaymentRequest\x1a\x10.payment.Payment\x12\\\n" +
	"\x17InitiateMetaMaskPayment\x12\x1f.payment.MetaMaskPaymentRequest\x1a .payment.MetaMaskPaymentResponse\x12R\n" +
	"\x16ConfirmMetaMaskPayment\x12&.payment.ConfirmMetaMaskPaymentRequest\x1a\x10.payment.Payment\x12:\n" +
	"\n" +
	"GetPayment\x12\x1a.payment.GetPaymentRequest\x1a\x10.payment.Payment\x12]\n" +
	"\x12GetPaymentsByOrder\x12\".payment.GetPaymentsByOrderRequest\x1a#.payment.GetPaymentsByOrderResponse\x12L\n" +
	"\x13UpdatePaymentStatus\x12#.payment.UpdatePaymentStatusRequest\x1a\x10.payment.Payment\x12]\n" +
	"\x12GetPendingPayments\x12\".payment.GetPendingPaymentsRequest\x1a#.payment.GetPendingPaymentsResponse\x12>\n" +
	"\fRetryPayment\x12\x1c.payment.RetryPaymentRequest\x1a\x10.payment.PaymentB/Z-github.com/yourusername/payment-service/protob\x06proto3"

var (
	file_payment_service_proto_payment_proto_rawDescOnce sync.Once
	file_payment_service_proto_payment_proto_rawDescData []byte
)

func file_payment_service_proto_payment_proto_rawDescGZIP() []byte {
	file_payment_service_proto_payment_proto_rawDescOnce.Do(func() {
		file_payment_service_proto_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_service_proto_payment_proto_rawDesc), len(file_payment_service_proto_payment_proto_rawDesc)))
	})
	return file_payment_service_proto_payment_proto_rawDescData
}

var file_payment_service_proto_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_payment_service_proto_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_payment_service_proto_payment_proto_goTypes = []any{
	(PaymentStatus)(0),                    // 0: payment.PaymentStatus
	(PaymentMethod)(0),                    // 1: payment.PaymentMethod
	(*Payment)(nil),                       // 2: payment.Payment
	(*InitiatePaymentRequest)(nil),        // 3: payment.InitiatePaymentRequest
	(*CreditCardPaymentRequest)(nil),      // 4: payment.CreditCardPaymentRequest
	(*CreditCardInfo)(nil),                // 5: payment.CreditCardInfo
	(*MetaMaskPaymentRequest)(nil),        // 6: payment.MetaMaskPaymentRequest
	(*MetaMaskPaymentResponse)(nil),       // 7: payment.MetaMaskPaymentResponse
	(*ConfirmMetaMaskPaymentRequest)(nil), // 8: payment.ConfirmMetaMaskPaymentRequest
	(*GetPaymentRequest)(nil),             // 9: payment.GetPaymentRequest
	(*GetPaymentsByOrderRequest)(nil),     // 10: payment.GetPaymentsByOrderRequest
	(*GetPaymentsByOrderResponse)(nil),    // 11: payment.GetPaymentsByOrderResponse
	(*UpdatePaymentStatusRequest)(nil),    // 12: payment.UpdatePaymentStatusRequest
	(*GetPendingPaymentsRequest)(nil),     // 13: payment.GetPendingPaymentsRequest
	(*GetPendingPaymentsResponse)(nil),    // 14: payment.GetPendingPaymentsResponse
	(*RetryPaymentRequest)(nil),           // 15: payment.RetryPaymentRequest
	(*timestamppb.Timestamp)(nil),         // 16: google.protobuf.Timestamp
}
var file_payment_service_proto_payment_proto_depIdxs = []int32{
	0,  // 0: payment.Payment.status:type_name -> payment.PaymentStatus
	1,  // 1: payment.Payment.payment_method:type_name -> payment.PaymentMethod
	16, // 2: payment.Payment.created_at:type_name -> google.protobuf.Timestamp
	16, // 3: payment.Payment.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: payment.InitiatePaymentRequest.payment_method:type_name -> payment.PaymentMethod
	5,  // 5: payment.CreditCardPaymentRequest.card_info:type_name -> payment.CreditCardInfo
	2,  // 6: payment.GetPaymentsByOrderResponse.payments:type_name -> payment.Payment
	0,  // 7: payment.UpdatePaymentStatusRequest.status:type_name -> payment.PaymentStatus
	2,  // 8: payment.GetPendingPaymentsResponse.payments:type_name -> payment.Payment
	1,  // 9: payment.RetryPaymentRequest.new_payment_method:type_name -> payment.PaymentMethod
	3,  // 10: payment.PaymentService.InitiatePayment:input_type -> payment.InitiatePaymentRequest
	4,  // 11: payment.PaymentService.ProcessCreditCardPayment:input_type -> payment.CreditCardPaymentRequest
	6,  // 12: payment.PaymentService.InitiateMetaMaskPayment:input_type -> payment.MetaMaskPaymentRequest
	8,  // 13: payment.PaymentService.ConfirmMetaMaskPayment:input_type -> payment.ConfirmMetaMaskPaymentRequest
	9,  // 14: payment.PaymentService.GetPayment:input_type -> payment.GetPaymentRequest
	10, // 15: payment.PaymentService.GetPaymentsByOrder:input_type -> payment.GetPaymentsByOrderRequest
	12, // 16: payment.PaymentService.UpdatePaymentStatus:input_type -> payment.UpdatePaymentStatusRequest
	13, // 17: payment.PaymentService.GetPendingPayments:input_type -> payment.GetPendingPaymentsRequest
	15, // 18: payment.PaymentService.RetryPayment:input_type -> payment.RetryPaymentRequest
	2,  // 19: payment.PaymentService.InitiatePayment:output_type -> payment.Payment
	2,  // 20: payment.PaymentService.ProcessCreditCardPayment:output_type -> payment.Payment
	7,  // 21: payment.PaymentService.InitiateMetaMaskPayment:output_type -> payment.MetaMaskPaymentResponse
	2,  // 22: payment.PaymentService.ConfirmMetaMaskPayment:output_type -> payment.Payment
	2,  // 23: payment.PaymentService.GetPayment:output_type -> payment.Payment
	11, // 24: payment.PaymentService.GetPaymentsByOrder:output_type -> payment.GetPaymentsByOrderResponse
	2,  // 25: payment.PaymentService.UpdatePaymentStatus:output_type -> payment.Payment
	14, // 26: payment.PaymentService.GetPendingPayments:output_type -> payment.GetPendingPaymentsResponse
	2,  // 27: payment.PaymentService.RetryPayment:output_type -> payment.Payment
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_payment_service_proto_payment_proto_init() }
func file_payment_service_proto_payment_proto_init() {
	if File_payment_service_proto_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_service_proto_payment_proto_rawDesc), len(file_payment_service_proto_payment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_service_proto_payment_proto_goTypes,
		DependencyIndexes: file_payment_service_proto_payment_proto_depIdxs,
		EnumInfos:         file_payment_service_proto_payment_proto_enumTypes,
		MessageInfos:      file_payment_service_proto_payment_proto_msgTypes,
	}.Build()
	File_payment_service_proto_payment_proto = out.File
	file_payment_service_proto_payment_proto_goTypes = nil
	file_payment_service_proto_payment_proto_depIdxs = nil
}
